Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list, while array_list is a NumPy array.

To print the data types of both variables, you can use the type() function in Python. Here's the code:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


The data type of list_ is <class 'list'> (Python list), and the data type of array_list is <class 'numpy.ndarray'> (NumPy array).

To print the data type of each element in both list_ and array_list, you can iterate over the elements and use the type() function. Here's the code:

In [3]:
import numpy as np
list_=['1,','2','3','4','5']
array_list=np.array(object=list_)
# Print data types of elements in list_
print("Data type of an element list_:")
for element in list_:
    print(type(element))
# Print data types of elements in array_list
print("\nData types of elements in array_list:")    
for element in array_list:
    print(type(element))

Data type of an element list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


The variable num_list is a Python list containing nested lists of integers. Each element in num_list is an integer.

The variable array_list is created by converting num_list into a NumPy array using the np.array() function. By specifying dtype = int, you are explicitly indicating that the data type of the elements in array_list should be integers.

Here's the corrected code and the data types of the elements in both variables:

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
array_list = np.array(num_list, dtype=int)

print("Data types in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

print("\nData types in array_list:")
for element in array_list.flatten():
    print(type(element))


Data types in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


The data types in num_list are standard Python integers (int), while the data types in array_list are NumPy integers (numpy.int64). NumPy uses its own data types to efficiently manage arrays, and in this case, it automatically converts the elements to numpy.int64.

In [6]:
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(num_list)
Shape=num_array.shape
Size=num_array.size
print("Shape of the num_array",Shape)
print("Size of the num_array",Size)

Shape of the num_array (2, 3)
Size of the num_array 6


The shape attribute returns a tuple representing the dimensions of the array, in this case, (2, 3), indicating that num_array has 2 rows and 3 columns.

The size attribute returns the total number of elements in the array, which is 6 in this case.

In [7]:
zero_array=np.zeros((3,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
